/*
===========================================================================
Copyright (C) 2026

This file is part of FnQL.

FnQL is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version.
===========================================================================
*/

#ifndef TR_GLX_PUBLIC_H
#define TR_GLX_PUBLIC_H

/*
 * Shared GLx compatibility vocabulary.
 *
 * Keep renderer-facing ids here instead of in the GLx module bridge so pure
 * classification logic and the legacy compatibility substrate do not need to
 * include the full GLx C ABI just to agree on counters, flags, and payload
 * shapes.
 */

#define GLX_DRAW_NONE -1
#define GLX_DRAW_GENERIC 0
#define GLX_DRAW_VBO_DEVICE 1
#define GLX_DRAW_VBO_SOFT 2
#define GLX_DRAW_DEBUG 3
#define GLX_DRAW_STREAM_GENERIC 4

#define GLX_LEGACY_DELEGATION_NONE -1
#define GLX_LEGACY_DELEGATION_GENERIC 0
#define GLX_LEGACY_DELEGATION_VBO_DEVICE 1
#define GLX_LEGACY_DELEGATION_VBO_SOFT 2
#define GLX_LEGACY_DELEGATION_DRAW_ARRAY 3
#define GLX_LEGACY_DELEGATION_REASON_COUNT 4

#define GLX_BATCH_VBO 0x0001
#define GLX_BATCH_FOG 0x0002
#define GLX_BATCH_MULTITEXTURE 0x0004
#define GLX_BATCH_POLYGON_OFFSET 0x0008

#define GLX_STAGE_PATH_GENERIC 0
#define GLX_STAGE_PATH_VBO 1

#define GLX_STAGE_MULTITEXTURE 0x0001
#define GLX_STAGE_DEPTH_FRAGMENT 0x0002
#define GLX_STAGE_BLEND 0x0004
#define GLX_STAGE_ALPHA_TEST 0x0008
#define GLX_STAGE_DEPTH_WRITE 0x0010
#define GLX_STAGE_LIGHTMAP 0x0020
#define GLX_STAGE_ANIMATED_IMAGE 0x0040
#define GLX_STAGE_VIDEO_MAP 0x0080
#define GLX_STAGE_SCREEN_MAP 0x0100
#define GLX_STAGE_DLIGHT_MAP 0x0200
#define GLX_STAGE_TEXMOD 0x0400
#define GLX_STAGE_ENVIRONMENT 0x0800
#define GLX_STAGE_ST0 0x1000
#define GLX_STAGE_ST1 0x2000
#define GLX_STAGE_SHADOW_PASS 0x4000
#define GLX_STAGE_BEAM_PASS 0x8000
#define GLX_STAGE_POSTPROCESS_PASS 0x10000
#define GLX_STAGE_DETAIL 0x20000

#define GLX_DLIGHT_STATE_LEGACY_PASS 0
#define GLX_DLIGHT_STATE_TEXTURE_BIND 1
#define GLX_DLIGHT_STATE_FOG_TEXTURE_BIND 2
#define GLX_DLIGHT_STATE_SHADOW_TEXTURE_BIND 3
#define GLX_DLIGHT_STATE_SHADOW_TEXTURE_FALLBACK_BIND 4
#define GLX_DLIGHT_STATE_SHADOW_FBO_BIND 5
#define GLX_DLIGHT_STATE_SHADOW_FBO_RESTORE 6
#define GLX_DLIGHT_STATE_GL_STATE 7
#define GLX_DLIGHT_STATE_COUNT 8

#define GLX_PROJECTED_DLIGHT_FLAG_ADDITIVE 0x00000001u
#define GLX_PROJECTED_DLIGHT_FLAG_LINEAR 0x00000002u
#define GLX_PROJECTED_DLIGHT_FLAG_FRONT_CULL 0x00000004u

typedef struct glxProjectedDlightRecord_s {
	float origin[3];
	float radius;
	float color[3];
	unsigned int flags;
} glxProjectedDlightRecord_t;

#define GLX_DYNAMIC_CATEGORY_ENTITY 0
#define GLX_DYNAMIC_CATEGORY_PARTICLE 1
#define GLX_DYNAMIC_CATEGORY_POLY 2
#define GLX_DYNAMIC_CATEGORY_MARK 3
#define GLX_DYNAMIC_CATEGORY_WEAPON 4
#define GLX_DYNAMIC_CATEGORY_UI 5
#define GLX_DYNAMIC_CATEGORY_BEAM 6
#define GLX_DYNAMIC_CATEGORY_DLIGHT 7
#define GLX_DYNAMIC_CATEGORY_SPECIAL 8
#define GLX_DYNAMIC_CATEGORY_COUNT 9

#define GLX_DYNAMIC_CATEGORY_MASK_ENTITY (1u << GLX_DYNAMIC_CATEGORY_ENTITY)
#define GLX_DYNAMIC_CATEGORY_MASK_PARTICLE (1u << GLX_DYNAMIC_CATEGORY_PARTICLE)
#define GLX_DYNAMIC_CATEGORY_MASK_POLY (1u << GLX_DYNAMIC_CATEGORY_POLY)
#define GLX_DYNAMIC_CATEGORY_MASK_MARK (1u << GLX_DYNAMIC_CATEGORY_MARK)
#define GLX_DYNAMIC_CATEGORY_MASK_WEAPON (1u << GLX_DYNAMIC_CATEGORY_WEAPON)
#define GLX_DYNAMIC_CATEGORY_MASK_UI (1u << GLX_DYNAMIC_CATEGORY_UI)
#define GLX_DYNAMIC_CATEGORY_MASK_BEAM (1u << GLX_DYNAMIC_CATEGORY_BEAM)
#define GLX_DYNAMIC_CATEGORY_MASK_DLIGHT (1u << GLX_DYNAMIC_CATEGORY_DLIGHT)
#define GLX_DYNAMIC_CATEGORY_MASK_SPECIAL (1u << GLX_DYNAMIC_CATEGORY_SPECIAL)
#define GLX_DYNAMIC_CATEGORY_MASK_ALL \
	(GLX_DYNAMIC_CATEGORY_MASK_ENTITY | GLX_DYNAMIC_CATEGORY_MASK_PARTICLE | \
	GLX_DYNAMIC_CATEGORY_MASK_POLY | GLX_DYNAMIC_CATEGORY_MASK_MARK | \
	GLX_DYNAMIC_CATEGORY_MASK_WEAPON | GLX_DYNAMIC_CATEGORY_MASK_UI | \
	GLX_DYNAMIC_CATEGORY_MASK_BEAM | GLX_DYNAMIC_CATEGORY_MASK_DLIGHT | \
	GLX_DYNAMIC_CATEGORY_MASK_SPECIAL)

#define GLX_IMAGE_COLORSPACE_UNKNOWN 0
#define GLX_IMAGE_COLORSPACE_SRGB 1
#define GLX_IMAGE_COLORSPACE_LINEAR 2
#define GLX_IMAGE_COLORSPACE_DATA 3
#define GLX_IMAGE_COLORSPACE_COUNT 4

#define GLX_MATERIAL_COMBINE_INVALID 0
#define GLX_MATERIAL_COMBINE_MODULATE 1
#define GLX_MATERIAL_COMBINE_ADD 2
#define GLX_MATERIAL_COMBINE_REPLACE 3
#define GLX_MATERIAL_COMBINE_DECAL 4

/*
 * Material-stage language ids mirror the renderer's id Tech 3 shader-stage
 * enums without requiring pure GLx logic to include renderer-private headers.
 */
#define GLX_MATERIAL_RGBGEN_BAD 0
#define GLX_MATERIAL_RGBGEN_IDENTITY_LIGHTING 1
#define GLX_MATERIAL_RGBGEN_IDENTITY 2
#define GLX_MATERIAL_RGBGEN_ENTITY 3
#define GLX_MATERIAL_RGBGEN_ONE_MINUS_ENTITY 4
#define GLX_MATERIAL_RGBGEN_EXACT_VERTEX 5
#define GLX_MATERIAL_RGBGEN_VERTEX 6
#define GLX_MATERIAL_RGBGEN_ONE_MINUS_VERTEX 7
#define GLX_MATERIAL_RGBGEN_WAVEFORM 8
#define GLX_MATERIAL_RGBGEN_LIGHTING_DIFFUSE 9
#define GLX_MATERIAL_RGBGEN_FOG 10
#define GLX_MATERIAL_RGBGEN_CONST 11

#define GLX_MATERIAL_ALPHAGEN_IDENTITY 0
#define GLX_MATERIAL_ALPHAGEN_SKIP 1
#define GLX_MATERIAL_ALPHAGEN_ENTITY 2
#define GLX_MATERIAL_ALPHAGEN_ONE_MINUS_ENTITY 3
#define GLX_MATERIAL_ALPHAGEN_VERTEX 4
#define GLX_MATERIAL_ALPHAGEN_ONE_MINUS_VERTEX 5
#define GLX_MATERIAL_ALPHAGEN_LIGHTING_SPECULAR 6
#define GLX_MATERIAL_ALPHAGEN_WAVEFORM 7
#define GLX_MATERIAL_ALPHAGEN_PORTAL 8
#define GLX_MATERIAL_ALPHAGEN_CONST 9

#define GLX_MATERIAL_TCGEN_BAD 0
#define GLX_MATERIAL_TCGEN_IDENTITY 1
#define GLX_MATERIAL_TCGEN_LIGHTMAP 2
#define GLX_MATERIAL_TCGEN_TEXTURE 3
#define GLX_MATERIAL_TCGEN_ENVIRONMENT_MAPPED 4
#define GLX_MATERIAL_TCGEN_ENVIRONMENT_MAPPED_FP 5
#define GLX_MATERIAL_TCGEN_FOG 6
#define GLX_MATERIAL_TCGEN_VECTOR 7

#define GLX_MATERIAL_WAVEFUNC_NONE 0
#define GLX_MATERIAL_WAVEFUNC_SIN 1
#define GLX_MATERIAL_WAVEFUNC_SQUARE 2
#define GLX_MATERIAL_WAVEFUNC_TRIANGLE 3
#define GLX_MATERIAL_WAVEFUNC_SAWTOOTH 4
#define GLX_MATERIAL_WAVEFUNC_INVERSE_SAWTOOTH 5
#define GLX_MATERIAL_WAVEFUNC_NOISE 6

#define GLX_MATERIAL_TMOD_NONE_BIT 0x00000001u
#define GLX_MATERIAL_TMOD_TRANSFORM_BIT 0x00000002u
#define GLX_MATERIAL_TMOD_TURBULENT_BIT 0x00000004u
#define GLX_MATERIAL_TMOD_SCROLL_BIT 0x00000008u
#define GLX_MATERIAL_TMOD_SCALE_BIT 0x00000010u
#define GLX_MATERIAL_TMOD_STRETCH_BIT 0x00000020u
#define GLX_MATERIAL_TMOD_ROTATE_BIT 0x00000040u
#define GLX_MATERIAL_TMOD_ENTITY_TRANSLATE_BIT 0x00000080u
#define GLX_MATERIAL_TMOD_OFFSET_BIT 0x00000100u
#define GLX_MATERIAL_TMOD_SCALE_OFFSET_BIT 0x00000200u
#define GLX_MATERIAL_TMOD_OFFSET_SCALE_BIT 0x00000400u
#define GLX_MATERIAL_TMOD_UNKNOWN_BIT 0x80000000u
#define GLX_MATERIAL_TMOD_KNOWN_BITS \
	(GLX_MATERIAL_TMOD_NONE_BIT | GLX_MATERIAL_TMOD_TRANSFORM_BIT | \
	GLX_MATERIAL_TMOD_TURBULENT_BIT | GLX_MATERIAL_TMOD_SCROLL_BIT | \
	GLX_MATERIAL_TMOD_SCALE_BIT | GLX_MATERIAL_TMOD_STRETCH_BIT | \
	GLX_MATERIAL_TMOD_ROTATE_BIT | GLX_MATERIAL_TMOD_ENTITY_TRANSLATE_BIT | \
	GLX_MATERIAL_TMOD_OFFSET_BIT | GLX_MATERIAL_TMOD_SCALE_OFFSET_BIT | \
	GLX_MATERIAL_TMOD_OFFSET_SCALE_BIT)

#define GLX_MATERIAL_TMOD_OPCODE_NONE 0
#define GLX_MATERIAL_TMOD_OPCODE_TRANSFORM 1
#define GLX_MATERIAL_TMOD_OPCODE_TURBULENT 2
#define GLX_MATERIAL_TMOD_OPCODE_SCROLL 3
#define GLX_MATERIAL_TMOD_OPCODE_SCALE 4
#define GLX_MATERIAL_TMOD_OPCODE_STRETCH 5
#define GLX_MATERIAL_TMOD_OPCODE_ROTATE 6
#define GLX_MATERIAL_TMOD_OPCODE_ENTITY_TRANSLATE 7
#define GLX_MATERIAL_TMOD_OPCODE_OFFSET 8
#define GLX_MATERIAL_TMOD_OPCODE_SCALE_OFFSET 9
#define GLX_MATERIAL_TMOD_OPCODE_OFFSET_SCALE 10
#define GLX_MATERIAL_TMOD_OPCODE_UNKNOWN 15
#define GLX_MATERIAL_TMOD_SEQUENCE_SLOT_BITS 4
#define GLX_MATERIAL_TMOD_SEQUENCE_SLOT_MASK 0x0fu
#define GLX_MATERIAL_TMOD_SEQUENCE_MAX_SLOTS 5

/*
 * These mirror the compatibility renderer's GLS_* stage state bits. GLx keeps
 * the raw state word in material keys, but exposes the fields here so pure GLx
 * GLSL permutation logic can distinguish blend, depth, and alpha-test variants
 * without including renderer-private headers.
 */
#define GLX_MATERIAL_STATE_SRCBLEND_ZERO 0x00000001u
#define GLX_MATERIAL_STATE_SRCBLEND_ONE 0x00000002u
#define GLX_MATERIAL_STATE_SRCBLEND_DST_COLOR 0x00000003u
#define GLX_MATERIAL_STATE_SRCBLEND_ONE_MINUS_DST_COLOR 0x00000004u
#define GLX_MATERIAL_STATE_SRCBLEND_SRC_ALPHA 0x00000005u
#define GLX_MATERIAL_STATE_SRCBLEND_ONE_MINUS_SRC_ALPHA 0x00000006u
#define GLX_MATERIAL_STATE_SRCBLEND_DST_ALPHA 0x00000007u
#define GLX_MATERIAL_STATE_SRCBLEND_ONE_MINUS_DST_ALPHA 0x00000008u
#define GLX_MATERIAL_STATE_SRCBLEND_ALPHA_SATURATE 0x00000009u
#define GLX_MATERIAL_STATE_SRCBLEND_BITS 0x0000000fu

#define GLX_MATERIAL_STATE_DSTBLEND_ZERO 0x00000010u
#define GLX_MATERIAL_STATE_DSTBLEND_ONE 0x00000020u
#define GLX_MATERIAL_STATE_DSTBLEND_SRC_COLOR 0x00000030u
#define GLX_MATERIAL_STATE_DSTBLEND_ONE_MINUS_SRC_COLOR 0x00000040u
#define GLX_MATERIAL_STATE_DSTBLEND_SRC_ALPHA 0x00000050u
#define GLX_MATERIAL_STATE_DSTBLEND_ONE_MINUS_SRC_ALPHA 0x00000060u
#define GLX_MATERIAL_STATE_DSTBLEND_DST_ALPHA 0x00000070u
#define GLX_MATERIAL_STATE_DSTBLEND_ONE_MINUS_DST_ALPHA 0x00000080u
#define GLX_MATERIAL_STATE_DSTBLEND_BITS 0x000000f0u

#define GLX_MATERIAL_STATE_BLEND_BITS \
	(GLX_MATERIAL_STATE_SRCBLEND_BITS | GLX_MATERIAL_STATE_DSTBLEND_BITS)
#define GLX_MATERIAL_STATE_DEPTHMASK_TRUE 0x00000100u
#define GLX_MATERIAL_STATE_POLYMODE_LINE 0x00000200u
#define GLX_MATERIAL_STATE_DEPTHTEST_DISABLE 0x00000400u
#define GLX_MATERIAL_STATE_DEPTHFUNC_EQUAL 0x00000800u
#define GLX_MATERIAL_STATE_ATEST_GT_0 0x00001000u
#define GLX_MATERIAL_STATE_ATEST_LT_80 0x00002000u
#define GLX_MATERIAL_STATE_ATEST_GE_80 0x00003000u
#define GLX_MATERIAL_STATE_ATEST_BITS 0x00003000u
#define GLX_MATERIAL_STATE_KNOWN_BITS \
	(GLX_MATERIAL_STATE_BLEND_BITS | GLX_MATERIAL_STATE_DEPTHMASK_TRUE | \
	GLX_MATERIAL_STATE_POLYMODE_LINE | GLX_MATERIAL_STATE_DEPTHTEST_DISABLE | \
	GLX_MATERIAL_STATE_DEPTHFUNC_EQUAL | GLX_MATERIAL_STATE_ATEST_BITS)

#define GLX_MATERIAL_FOG_ADJUST_NONE 0
#define GLX_MATERIAL_FOG_ADJUST_MODULATE_RGB 1
#define GLX_MATERIAL_FOG_ADJUST_MODULATE_RGBA 2
#define GLX_MATERIAL_FOG_ADJUST_MODULATE_ALPHA 3

#define GLX_STREAM_SKIP_NO_BIND_BUFFER 0
#define GLX_STREAM_SKIP_BAD_INPUT 1
#define GLX_STREAM_SKIP_MULTITEXTURE 2
#define GLX_STREAM_SKIP_DEPTH_FRAGMENT 3
#define GLX_STREAM_SKIP_NO_TEXCOORDS 4
#define GLX_STREAM_SKIP_EMPTY_BATCH 5
#define GLX_STREAM_SKIP_MATERIAL_KEY 6
#define GLX_STREAM_SKIP_FOG 7
#define GLX_STREAM_SKIP_MATERIAL_PROGRAM 8

#define GLX_POSTPROCESS_RESULT_NONE 0
#define GLX_POSTPROCESS_RESULT_BLOOM_FINAL 1
#define GLX_POSTPROCESS_RESULT_GAMMA_DIRECT 2
#define GLX_POSTPROCESS_RESULT_GAMMA_BLIT 3
#define GLX_POSTPROCESS_RESULT_MINIMIZED 4

#define GLX_BLOOM_CREATE_NONE 0
#define GLX_BLOOM_CREATE_SUCCESS 1
#define GLX_BLOOM_CREATE_TEXTURE_UNITS 2
#define GLX_BLOOM_CREATE_FBO 3

#define GLX_BLOOM_RESULT_NONE 0
#define GLX_BLOOM_RESULT_SKIPPED 1
#define GLX_BLOOM_RESULT_INTERMEDIATE 2
#define GLX_BLOOM_RESULT_FINAL 3
#define GLX_BLOOM_RESULT_CREATE_FAILED 4

#define GLX_HDR_BLOOM_FORMAT_AUTO 0
#define GLX_HDR_BLOOM_FORMAT_RGBA16F 1
#define GLX_HDR_BLOOM_FORMAT_R11G11B10F 2
#define GLX_HDR_BLOOM_FORMAT_RG16F 3

#define GLX_AUTO_EXPOSURE_OFF 0
#define GLX_AUTO_EXPOSURE_TIERED 1
#define GLX_AUTO_EXPOSURE_SIMPLE 2
#define GLX_AUTO_EXPOSURE_HISTOGRAM 3

#define GLX_FBO_BLIT_MS 1
#define GLX_FBO_BLIT_SS 2
#define GLX_FBO_BLIT_BACKBUFFER 3
#define GLX_FBO_BLIT_COPY_SCREEN 4

#define GLX_FLARE_CONTRACT_LEGACY 0
#define GLX_FLARE_CONTRACT_SCENE_LINEAR 1

#define GLX_GPU_PASS_BACKEND 0
#define GLX_GPU_PASS_POSTPROCESS 1
#define GLX_GPU_PASS_BLOOM 2
#define GLX_GPU_PASS_BLOOM_EXTRACT 3
#define GLX_GPU_PASS_BLOOM_DOWNSCALE 4
#define GLX_GPU_PASS_BLOOM_BLUR 5
#define GLX_GPU_PASS_BLOOM_BLEND 6
#define GLX_GPU_PASS_BLOOM_FINAL 7
#define GLX_GPU_PASS_BLOOM_LENS_REFLECTION 8
#define GLX_GPU_PASS_GAMMA_DIRECT 9
#define GLX_GPU_PASS_GAMMA_BLIT 10
#define GLX_GPU_PASS_FBO_BLIT 11
#define GLX_GPU_PASS_COPY_SCREEN 12
#define GLX_GPU_PASS_FLARE 13
#define GLX_GPU_PASS_DLIGHT_SHADOW 14
#define GLX_GPU_PASS_CSM_SHADOW 15
#define GLX_GPU_PASS_COUNT 16

typedef struct glxStreamReservation_s {
	unsigned int buffer;
	unsigned int offset;
	unsigned int bytes;
	void *ptr;
	int strategy;
	int mapped;
	int committed;
	unsigned int reserveWraps;
	unsigned int reserveSameFrameWrapRejects;
	unsigned int reserveSyncWaits;
	unsigned int reserveSyncTimeouts;
	unsigned int reserveSyncFailures;
} glxStreamReservation_t;

#endif // TR_GLX_PUBLIC_H
