from __future__ import annotations

import argparse
import json
import math
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = ROOT / ".tmp" / "dlight-shadow-tests"
CLIENT_NAME_RE = re.compile(r"^fnql(?:\.[A-Za-z0-9_]+)?(?:\.exe)?$", re.IGNORECASE)
CVAR_NAME_RE = re.compile(r"^[A-Za-z0-9_]+$")
Q3_COMMAND_TOKEN_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.\-/]*$")
FS_GAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def command_to_string(command: list[str]) -> str:
    if os.name == "nt":
        return subprocess.list2cmdline(command)
    import shlex

    return shlex.join(command)


def q3_path(path: Path) -> str:
    return str(path).replace("\\", "/")


def q3_quote(value: object) -> str:
    text = str(value).replace("\\", "/").replace('"', '\\"')
    return f'"{text}"'


def sanitize(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "-", value.strip())
    return cleaned.strip("-") or "item"


def validate_q3_command_token(value: str, option: str) -> str:
    token = value.strip()
    parts = token.split("/")
    if (
        not Q3_COMMAND_TOKEN_RE.fullmatch(token)
        or any(part in {"", ".", ".."} for part in parts)
    ):
        raise ValueError(f"{option} must be a safe Quake 3 qpath token")
    return token


def validate_fs_game(value: str) -> str:
    name = value.strip()
    if not name:
        return ""
    if (
        not FS_GAME_RE.fullmatch(name)
        or name in {".", ".."}
        or name.startswith(".")
    ):
        raise ValueError("--fs-game must be a single safe mod directory name")
    return name


def validate_cvar_assignment(name: str, value: str) -> tuple[str, str]:
    cvar = name.strip()
    if not cvar:
        raise ValueError("--extra-set cvar name must not be empty")
    if not CVAR_NAME_RE.fullmatch(cvar):
        raise ValueError(f"--extra-set cvar name is not safe: {name!r}")
    if any(char in value for char in ("\r", "\n", "\x00", ";")):
        raise ValueError(f"--extra-set value for {cvar!r} contains an unsafe control character")
    return cvar, value.strip()


def resolve_path(value: str | None) -> Path | None:
    if value is None:
        return None
    path = Path(value)
    if not path.is_absolute():
        path = ROOT / path
    return path


def executable_rank(path: Path) -> tuple[int, int, str]:
    lower_parts = [part.lower() for part in path.parts]
    name = path.name.lower()
    penalty = 0
    if "meson-private" in lower_parts or "cmakefiles" in lower_parts:
        penalty += 100
    if "subprojects" in lower_parts:
        penalty += 100
    if ".tmp" in lower_parts:
        penalty += 5
    if ".ded." in name or name.endswith(".ded.exe"):
        penalty += 50
    return (penalty, len(path.parts), str(path))


def find_executable(search_roots: list[Path]) -> Path | None:
    candidates: list[Path] = []
    for root in search_roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file() and CLIENT_NAME_RE.match(path.name):
                candidates.append(path)
    if not candidates:
        return None
    return sorted(candidates, key=executable_rank)[0]


def parse_extra_sets(values: list[str]) -> dict[str, str]:
    result: dict[str, str] = {}
    for item in values:
        if "=" not in item:
            raise ValueError(f"--extra-set expects NAME=VALUE, got {item!r}")
        name, value = item.split("=", 1)
        name, value = validate_cvar_assignment(name, value)
        result[name] = value
    return result


def require_finite(value: float, option: str) -> None:
    if not math.isfinite(value):
        raise ValueError(f"{option} must be finite")


def require_positive(value: float, option: str) -> None:
    require_finite(value, option)
    if value <= 0:
        raise ValueError(f"{option} must be positive")


def require_non_negative(value: float, option: str) -> None:
    require_finite(value, option)
    if value < 0:
        raise ValueError(f"{option} must be non-negative")


def write_config(
    path: Path,
    *,
    map_name: str,
    count: int,
    intensity: float,
    distance: float,
    height: float,
    seconds: float,
    cvars: dict[str, str],
) -> None:
    lines = [
        "// Generated by scripts/dlight_shadow_test.py.",
        "// Keep persistent test data under .tmp; do not ship this config.",
    ]
    for name in sorted(cvars):
        lines.append(f"seta {name} {q3_quote(cvars[name])}")
    lines.extend(
        [
            f"devmap {map_name}",
            "wait",
            "wait",
            f"r_dlightTest {count} {intensity:g} {distance:g} {height:g} {seconds:g}",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_engine_command(
    args: argparse.Namespace, cfg_name: str, startup_cvars: dict[str, str]
) -> list[str]:
    assert args.exe is not None
    command = [
        str(args.exe),
        "+set",
        "fs_homepath",
        q3_path(args.homepath),
        "+set",
        "fs_basepath",
        q3_path(args.basepath),
        "+set",
        "cl_renderer",
        args.renderer,
    ]
    for name in sorted(startup_cvars):
        command.extend(["+set", name, startup_cvars[name]])
    if args.fs_game:
        command.extend(["+set", "fs_game", args.fs_game])
    command.extend(["+exec", cfg_name])
    return command


def wrap_renderdoc(command: list[str], args: argparse.Namespace) -> list[str]:
    capture_file = args.capture_file
    capture_file.parent.mkdir(parents=True, exist_ok=True)
    wrapped = [
        args.renderdoccmd,
        "capture",
        "--wait-for-exit",
        "--capture-file",
        str(capture_file),
    ]
    wrapped.extend(args.renderdoc_arg)
    wrapped.extend(command)
    return wrapped


def run_command(command: list[str], cwd: Path, timeout: float) -> int:
    completed = subprocess.run(command, cwd=str(cwd), timeout=timeout, check=False)
    return completed.returncode


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Launch a repeatable GLx/Vulkan dynamic-light shadow test scene."
    )
    parser.add_argument("--renderer", choices=("glx", "vk"), default="vk")
    parser.add_argument("--exe", help="Path to the FnQL client executable.")
    parser.add_argument(
        "--search-root",
        action="append",
        default=[],
        help="Additional directory to search when --exe is omitted.",
    )
    parser.add_argument("--basepath", default=str(ROOT), help="Engine fs_basepath.")
    parser.add_argument(
        "--homepath",
        help="Engine fs_homepath. Defaults to a renderer-specific directory under .tmp.",
    )
    parser.add_argument("--fs-game", default="", help="Optional fs_game value.")
    parser.add_argument("--map", default="q3dm17", help="Map to load for the test.")
    parser.add_argument("--count", type=int, default=8, help="Number of test dlights.")
    parser.add_argument("--intensity", type=float, default=360.0)
    parser.add_argument("--distance", type=float, default=224.0)
    parser.add_argument("--height", type=float, default=32.0)
    parser.add_argument("--seconds", type=float, default=20.0)
    parser.add_argument(
        "--max-lights",
        type=int,
        help="r_dlightShadowMaxLights. Defaults to the test dlight count.",
    )
    parser.add_argument("--resolution", type=int, default=256)
    parser.add_argument(
        "--extra-set",
        action="append",
        default=[],
        metavar="NAME=VALUE",
        help="Additional cvar to write to the generated test config.",
    )
    parser.add_argument("--output-root", default=str(DEFAULT_OUTPUT_ROOT))
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--timeout", type=float, default=180.0)
    parser.add_argument(
        "--renderdoc",
        action="store_true",
        help="Launch through renderdoccmd capture.",
    )
    parser.add_argument("--renderdoccmd", default="renderdoccmd")
    parser.add_argument(
        "--renderdoc-arg",
        action="append",
        default=[],
        help="Extra renderdoccmd capture argument inserted before the executable.",
    )
    parser.add_argument(
        "--capture-file",
        help="RenderDoc .rdc output path. Defaults under the output root.",
    )
    args = parser.parse_args(argv)

    args.basepath = resolve_path(args.basepath)
    args.output_root = resolve_path(args.output_root)
    if args.homepath:
        args.homepath = resolve_path(args.homepath)
    else:
        args.homepath = args.output_root / "home" / args.renderer
    args.exe = resolve_path(args.exe)
    args.search_root = [resolve_path(path) for path in args.search_root]
    args.capture_file = resolve_path(args.capture_file)
    if args.capture_file is None:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        args.capture_file = (
            args.output_root
            / "captures"
            / f"dlight-shadow-{sanitize(args.renderer)}-{timestamp}.rdc"
        )

    if args.count < 1:
        parser.error("--count must be at least 1")
    if args.max_lights is None:
        args.max_lights = args.count
    if args.max_lights < 1:
        parser.error("--max-lights must be at least 1")
    if args.resolution < 64:
        parser.error("--resolution must be at least 64")
    try:
        args.fs_game = validate_fs_game(args.fs_game)
        args.map = validate_q3_command_token(args.map, "--map")
        require_positive(args.intensity, "--intensity")
        require_positive(args.distance, "--distance")
        require_finite(args.height, "--height")
        require_non_negative(args.seconds, "--seconds")
        require_positive(args.timeout, "--timeout")
    except ValueError as exc:
        parser.error(str(exc))
    return args


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    search_roots = [
        *(path for path in args.search_root if path is not None),
        ROOT / ".tmp",
        ROOT / "build",
        ROOT / "meson" / "build",
    ]
    if args.exe is None:
        args.exe = find_executable(search_roots)
    if args.exe is None:
        print("No FnQL client executable found. Pass --exe.", file=sys.stderr)
        return 2
    if not args.dry_run and not args.exe.exists():
        print(f"Executable does not exist: {args.exe}", file=sys.stderr)
        return 2

    test_tag = f"dlight-shadow-{sanitize(args.renderer)}"
    game_dir = args.fs_game if args.fs_game else "baseq3"
    cfg_name = f"{test_tag}.cfg"
    cfg_path = args.homepath / game_dir / cfg_name
    cvars = {
        "developer": "1",
        "logfile": "2",
        "r_dynamiclight": "1",
        "r_dlightMode": "1",
        "r_dlightShadows": "1",
        "r_dlightShadowDebug": "1",
        "r_dlightShadowMaxLights": str(args.max_lights),
        "r_dlightShadowResolution": str(args.resolution),
        "r_fullscreen": "0",
        "r_mode": "-1",
        "r_speeds": "4",
        "r_swapInterval": "0",
    }
    cvars.update(parse_extra_sets(args.extra_set))
    write_config(
        cfg_path,
        map_name=args.map,
        count=args.count,
        intensity=args.intensity,
        distance=args.distance,
        height=args.height,
        seconds=args.seconds,
        cvars=cvars,
    )

    command = build_engine_command(args, cfg_name, cvars)
    if args.renderdoc:
        command = wrap_renderdoc(command, args)

    manifest = {
        "version": 1,
        "createdUtc": datetime.now(timezone.utc).isoformat(),
        "renderer": args.renderer,
        "map": args.map,
        "config": str(cfg_path),
        "homepath": str(args.homepath),
        "basepath": str(args.basepath),
        "renderdoc": bool(args.renderdoc),
        "captureFile": str(args.capture_file) if args.renderdoc else None,
        "command": command,
        "commandLine": command_to_string(command),
        "dryRun": bool(args.dry_run),
    }
    manifest_path = args.output_root / f"{test_tag}.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(command_to_string(command))
    print(f"Config: {cfg_path}")
    print(f"Manifest: {manifest_path}")
    if args.dry_run:
        return 0
    return run_command(command, ROOT, args.timeout)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
